#!/usr/bin/perl

##############################
#
# collect mcs/proxy log file
#
##############################

use strict;
use warnings;
use Net::SCP::Expect;
use Getopt::Long;
use Net::OpenSSH;

my $server = "1.1.1.1";
my $proxy  = "1.1.1.1";

GetOptions("server=s"	=> \$server,
           "proxy=s"	=> \$proxy)
or die("Error in command line argument\n");

sub printServerInfo(){
	print "MCS: \$mcsHostname\n";
	print "MCS ip: \$mcsIp\n";
	print "MCS build: \$mcsBuild\n";
}

sub printProxyInfo(){
	print "Proxy: \$proxyHostname\n";
	print "Proxy ip: \$proxyIp\n";
	print "Proxy build: \$proxyBuild\n";
}

# Get 3 last log file on proxy
sub getProxyLog(){
	my $ssh1 = Net::OpenSSH->new("root\@$proxy",password => 'avam@r');
	my @output = $ssh1->capture('ls -rt /usr/local/avamarclient/var/*.log | tail -n 3');
	chomp(@output);
	my $scpe = Net::SCP::Expect->new(host=>$server,user=>'root',password=>'avam@r');
	$scpe->login('root','avam@r');
	foreach my $logfile (@output){
		$scpe->scp("root\@$proxy:$logfile");
	}
}